norminette ../ex00/ft_ft.c -R CheckForbiddenSourceHeader
norminette ../ex01/ft_ultimate_ft.c -R CheckForbiddenSourceHeader
norminette ../ex02/ft_swap.c -R CheckForbiddenSourceHeader
norminette ../ex03/ft_div_mod.c -R CheckForbiddenSourceHeader
norminette ../ex04/ft_ultimate_div_mod.c -R CheckForbiddenSourceHeader
norminette ../ex05/ft_putstr.c -R CheckForbiddenSourceHeader
norminette ../ex06/ft_strlen.c -R CheckForbiddenSourceHeader
norminette ../ex07/ft_rev_int_tab.c -R CheckForbiddenSourceHeader
norminette ../ex08/ft_sort_int_tab.c -R CheckForbiddenSourceHeader
