gcc main00.c -o test00 -Wall -Wextra -Werror
gcc main01.c -o test01 -Wall -Wextra -Werror
gcc main02.c -o test02 -Wall -Wextra -Werror
gcc main03.c -o test03 -Wall -Wextra -Werror
gcc main04.c -o test04 -Wall -Wextra -Werror
gcc main05.c -o test05 -Wall -Wextra -Werror
gcc main06.c -o test06 -Wall -Wextra -Werror
gcc main07.c -o test07 -Wall -Wextra -Werror
gcc main08.c -o test08 -Wall -Wextra -Werror
gcc main09.c -o test09 -Wall -Wextra -Werror
gcc main10.c -o test10 -Wall -Wextra -Werror
gcc main11.c -o test11 -Wall -Wextra -Werror
gcc main12.c -o test12 -Wall -Wextra -Werror
