norminette ../ex00/ft_putchar.c -R CheckForbiddenSourceHeader
norminette ../ex01/ft_print_alphabet.c -R CheckForbiddenSourceHeader
norminette ../ex02/ft_print_reverse_alphabet.c -R CheckForbiddenSourceHeader
norminette ../ex03/ft_print_numbers.c -R CheckForbiddenSourceHeader
norminette ../ex04/ft_is_negative.c -R CheckForbiddenSourceHeader
norminette ../ex05/ft_print_comb.c -R CheckForbiddenSourceHeader
norminette ../ex06/ft_print_comb2.c -R CheckForbiddenSourceHeader
norminette ../ex07/ft_putnbr.c -R CheckForbiddenSourceHeader
norminette ../ex08/ft_print_combn.c -R CheckForbiddenSourceHeader
