norminette ../ex00/ -R CheckForbiddenSourceHeader
norminette ../ex01/ -R CheckForbiddenSourceHeader
norminette ../ex02/ -R CheckForbiddenSourceHeader
norminette ../ex03/ -R CheckForbiddenSourceHeader
norminette ../ex04/ -R CheckForbiddenSourceHeader
norminette ../ex05/ -R CheckForbiddenSourceHeader
norminette ../ex06/ -R CheckForbiddenSourceHeader
norminette ../ex07/ -R CheckForbiddenSourceHeader
norminette ../ex08/ -R CheckForbiddenSourceHeader
